import { Session } from "@/declarations";

export const mockPatients = [
  { id: 1, name: "Ayşe Kaya" },
  { id: 2, name: "Mehmet Demir" },
  { id: 3, name: "Zeynep Yılmaz" },
  { id: 4, name: "Ahmet Yıldız" },
  { id: 5, name: "Can Öztürk" },
  { id: 6, name: "Elif Şahin" },
];

export const mockSessions: Session[] = [
  {
    id: "1",
    patientName: "Ayşe Kaya",
    type: "record",
    status: "stopped",
    diagnosis: "Anksiyete Bozukluğu",
    title: "İlk Değerlendirme Seansı",
    content: "Hasta son zamanlarda artan kaygı belirtileri gösteriyor. Özellikle iş yerinde yaşanan stres faktörleri...",
    created_at: new Date("2024-03-15T10:00:00"),
    updated_at: new Date("2024-03-15T11:00:00"),
  },
  {
    id: "2",
    patientName: "Mehmet Demir",
    type: "dictate",
    status: "error",
    diagnosis: "Major Depresyon",
    title: "Takip Seansı",
    content: "İlaç tedavisine olumlu yanıt alınıyor. Uyku düzeni iyileşme göstermeye başladı...",
    created_at: new Date("2024-03-14T15:30:00"),
    updated_at: new Date("2024-03-14T16:15:00"),
  },
  {
    id: "3",
    patientName: "Zeynep Yılmaz",
    type: "note",
    status: "generating",
    diagnosis: "DEHB",
    title: "Kontrol Seansı",
    content: "Akademik performansta iyileşme gözlemleniyor. Ev ödevleri tamamlanmış...",
    created_at: new Date("2024-03-13T09:00:00"),
    updated_at: new Date("2024-03-13T09:45:00"),
  },
  {
    id: "4",
    patientName: "Can Öztürk",
    type: "record",
    status: "done",
    diagnosis: "OKB",
    title: "Terapi Seansı",
    content: "Maruz bırakma egzersizlerine devam ediliyor. Ritüellerin sıklığında azalma...",
    created_at: new Date("2024-03-12T14:00:00"),
    updated_at: new Date("2024-03-12T15:00:00"),
  },
  {
    id: "5",
    patientName: "Elif Şahin",
    type: "dictate",
    status: "done",
    diagnosis: "Sosyal Anksiyete",
    title: "İlk Görüşme",
    content: "Sosyal ortamlarda yaşanan kaygı durumları değerlendirildi. Kaçınma davranışları...",
    created_at: new Date("2024-03-11T11:00:00"),
    updated_at: new Date("2024-03-11T12:00:00"),
  },
  {
    id: "6",
    patientName: "Ahmet Yıldız",
    type: "record",
    status: "in_progress",
    diagnosis: null,
    title: "Değerlendirme Seansı",
    content: "Görüşme devam ediyor...",
    created_at: new Date("2024-03-16T09:00:00"),
    updated_at: new Date("2024-03-16T09:30:00"),
  },
] as const; 