import { Session, Patient } from "@/declarations";

export const mockPatients: Patient[] = [
  {
    id: "1",
    name: "Ayşe Kaya",
    category: "personal",
    gender: "female",
    age: 28,
    diagnosis: "ICD-10: F41.9 - Anksiyete Bozukluğu",
    progress_summary: "Hasta düzenli olarak seanslarına katılıyor. Son 3 seansta kaygı seviyesinde belirgin azalma gözlemlendi. Uyku düzeni iyileşme gösteriyor. Sosyal aktivitelere katılım artmaya başladı.",
    profile_color: {
      light: "#E9D5FF",
      dark: "#A855F7"
    },
    created_at: "2024-03-01T10:00:00",
    updated_at: "2024-03-15T11:00:00",
  },
  {
    id: "2",
    name: "Mehmet Demir",
    category: "personal",
    gender: "male",
    age: 35,
    diagnosis: null,
    progress_summary: null,
    profile_color: {
      light: "#BFDBFE",
      dark: "#3B82F6"
    },
    created_at: "2024-03-02T14:30:00",
    updated_at: "2024-03-14T16:15:00",
  },
  {
    id: "3",
    name: "Zeynep Yılmaz",
    category: "child",
    gender: "female",
    age: 12,
    diagnosis: null,
    progress_summary: null,
    profile_color: {
      light: "#FBCFE8",
      dark: "#EC4899"
    },
    created_at: "2024-03-03T09:00:00",
    updated_at: "2024-03-13T09:45:00",
  },
  {
    id: "4",
    name: "Ahmet Yıldız",
    category: "personal",
    gender: "male",
    age: 42,
    diagnosis: null,
    progress_summary: null,
    profile_color: {
      light: "#99F6E4",
      dark: "#14B8A6"
    },
    created_at: "2024-03-04T11:00:00",
    updated_at: "2024-03-16T09:30:00",
  },
  {
    id: "5",
    name: "Can Öztürk",
    category: "personal",
    gender: "male",
    age: 29,
    diagnosis: "ICD-10: F42.2 - OKB",
    progress_summary: "Maruz bırakma egzersizleri olumlu sonuç veriyor. Ritüellerin sıklığı ve süresi azaldı. Günlük yaşam aktivitelerinde iyileşme var.",
    profile_color: {
      light: "#C7D2FE",
      dark: "#6366F1"
    },
    created_at: "2024-03-05T15:00:00",
    updated_at: "2024-03-12T15:00:00",
  },
  {
    id: "6",
    name: "Elif Şahin",
    category: "personal",
    gender: "female",
    age: 24,
    diagnosis: "ICD-10: F40.1 - Sosyal Anksiyete Bozukluğu",
    progress_summary: "Sosyal durumlarda kaygı seviyesi azalmaya başladı. Kaçınma davranışları azalıyor. İş yerinde iletişim becerileri gelişiyor.",
    profile_color: {
      light: "#FECDD3",
      dark: "#F43F5E"
    },
    created_at: "2024-03-06T10:30:00",
    updated_at: "2024-03-11T12:00:00",
  },
];

export const mockSessions: Session[] = [
  {
    id: "1",
    patientId: "1",
    patientName: "Ayşe Kaya",
    type: "record",
    status: "done",
    title: "İlk Değerlendirme Seansı",
    diagnosis: "ICD-10 Kodu: N39.0 - İdrar Yolu Enfeksiyonu",
    complaint:"İdrar yaparken zorlanma ve yanma hissi; sık sık tuvalete gitme ihtiyacı ancak az veya hiç idrar yapamama",
    story:"Hasta yaklaşık bir haftadır idrar yaparken sıkıntı yaşıyor. Sık sık tuvalete gitme ihtiyacı hissetmesine rağmen gittiğinde az miktarda veya hiç idrar yapamıyor. İdrar renginde koyulaşma ve yanma hissi olduğunu belirtti ancak idrarında kan görmemiş. Alt karın bölgesinde hafif ağrı hissediyor. Günlük su tüketimi düşük (yaklaşık bir litre).",
    clinical_findings:"Fizik muayenede belirgin bir anormallik saptanmadı. Hasta stresli bir dönem geçirmiyor.",
    treatment:"İdrar tahlili yapılması ve gerekirse ultrason tetkiki planlandı.",
    summary:"Muhtemel idrar yolu enfeksiyonu. İdrar tahlili yapılmalı ve gerekirse ultrason tetkiki planlanmalı.",
    created_at: new Date("2024-03-15T10:00:00"),
    updated_at: new Date("2024-03-15T11:00:00"),
  },
  {
    id: "2",
    patientId: "2",
    patientName: "Mehmet Demir",
    type: "dictate",
    status: "error",
    title: "Takip Seansı",
    diagnosis: "",
    complaint: null,
    story: null,
    clinical_findings: null,
    treatment: null,
    summary: null,
    created_at: new Date("2024-03-14T15:30:00"),
    updated_at: new Date("2024-03-14T16:15:00"),
  },
  {
    id: "3",
    patientId: "3",
    patientName: "Zeynep Yılmaz",
    type: "note",
    status: "generating",
    title: "Kontrol Seansı",
    diagnosis: "",
    complaint: null,
    story: null,
    clinical_findings: null,
    treatment: null,
    summary: null,
    created_at: new Date("2024-03-13T09:00:00"),
    updated_at: new Date("2024-03-13T09:45:00"),
  },
  {
    id: "4",
    patientId: "5",
    patientName: "Can Öztürk",
    type: "record",
    status: "done",
    title: "Terapi Seansı",
    diagnosis: "ICD-10: F42.2 - OKB",
    complaint: "Tekrarlayan kontrol davranışları ve temizlik takıntısı",
    story: "Hasta günde birkaç kez kapıları ve elektronik cihazları kontrol etme ihtiyacı hissediyor. Aşırı el yıkama davranışı mevcut. Bu durumlar günlük yaşamını ve iş performansını olumsuz etkiliyor.",
    clinical_findings: "Kompulsif kontrol ve temizlik davranışları belirgin. Anksiyete seviyesi yüksek.",
    treatment: "Maruz bırakma ve tepki önleme terapisi başlatıldı.",
    summary: "OKB semptomları belirgin. Davranışsal terapi ve ilaç tedavisi birlikte yürütülmeli.",
    created_at: new Date("2024-03-12T14:00:00"),
    updated_at: new Date("2024-03-12T15:00:00"),
  },
  {
    id: "5",
    patientId: "6",
    patientName: "Elif Şahin",
    type: "dictate",
    status: "done",
    title: "İlk Görüşme",
    diagnosis: "ICD-10: F40.1 - Sosyal Anksiyete Bozukluğu",
    complaint: "Sosyal ortamlarda aşırı kaygı ve performans anksiyetesi",
    story: "Hasta iş yerinde sunum yapmakta ve toplantılara katılmakta zorlanıyor. Sosyal ortamlarda yoğun kaygı yaşıyor ve bu durumlardan kaçınma davranışı gösteriyor.",
    clinical_findings: "Sosyal durumlarda belirgin anksiyete ve kaçınma davranışları mevcut.",
    treatment: "Bilişsel davranışçı terapi ve kademeli maruz bırakma planlandı.",
    summary: "Sosyal anksiyete bozukluğu tanısı konuldu. Sistematik duyarsızlaştırma tekniği uygulanacak.",
    created_at: new Date("2024-03-11T11:00:00"),
    updated_at: new Date("2024-03-11T12:00:00"),
  },
  {
    id: "6",
    patientId: "4",
    patientName: "Ahmet Yıldız",
    type: "record",
    status: "in_progress",
    title: "Değerlendirme Seansı",
    diagnosis: null,
    complaint: null,
    story: null,
    clinical_findings: null,
    treatment: null,
    summary: null,
    created_at: new Date("2024-03-16T09:00:00"),
    updated_at: new Date("2024-03-16T09:30:00"),
  },
];